### ISSUE TITLE
Update Dependencies: ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by SZRabinowitz** [cuuush/groupme-push#1]
Hi, when I install groupme-push, I have errors when trying to use it.

```
C:\Users\Admin\Downloads\gmpush-example>python bot.py
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\gmpush-example\bot.py", line 37, in <module>
    from botfunctions import startbot
  File "C:\Users\Admin\Downloads\gmpush-example\botfunctions\startbot.py", line 2, in <module>
    from groupme_push.client import PushClient
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\groupme_push\client.py", line 11, in <module>
    import requests
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

pip install --upgrade urllib3 solved the issue for me. So maybe you can update you pyproject.toml to use urllib3-2.1.0.

Will this cause any issues? I haven't come across any so far.

By the way I am on Windows 11, using Python 3.12.0. I think I only had the issue in this version, not Python 3.11.X.

**Comment by SZRabinowitz** [comment]
Clarification: I see your pyproject.toml doesn't even list urllib3, it's a requirement of requests. Installing the latest requests (requests-2.31.0) didn't either cause me issues in this case, so maybe that dependency should be updated? I only tried it on python 3.12.0 so I don't know if this would cause issues in later versions. 


(I might need to move back down my bot to 3.11 anyway, because the host I want to use doesn't support 3.12 yet)

**Comment by cuuush** [comment]
Thanks! Updated dependencies, tested on 3.10 and 3.12.
